### ISSUE TITLE
Need some help!

### ISSUE THREAD

**Issue by ashfaqconvo** [caioguedes/gearman-playground#1]
Hi,

How can I check worker is running or not ? by docker compose or docker container

**Comment by ashfaqconvo** [comment]
I can see docker container is running and I can ssh the worker container

**Comment by caioguedes** [comment]
Hello @ashfaqconvo,

Yeah, if the worker container has stopped, the worker is not running. You can also use `docker logs -f` to see if it has errors.

But if you want more details about the server, you should see this links:
https://github.com/gaspaio/gearmanui
https://github.com/yugene/Gearman-Monitor

I hope it helps! :D
